### ISSUE TITLE
"Upcoming events" is missing from homepage

### ISSUE THREAD

**Issue by anthonydillon** [canonical-websites/blog.ubuntu.com#16]
Maybe this is okay because we rarely have events anyway.

Split from: #4

**Comment by anthonydillon** [comment]
@pmahnke @frankiegranato what do you think? Kill events?

**Comment by pmahnke** [comment]
@anthonydillon I think this is a question for Thibaut

**Comment by anthonydillon** [comment]
I spoke to Thibaut and as we are doing events now we should have events in
the homepage.

**Comment by anasereijo** [comment]
this is done.
