### ISSUE TITLE
EVENTS no longer working on Ubuntu Insights

### ISSUE THREAD

**Issue by lamesdonner** [canonical-websites/blog.ubuntu.com#234]
Hello,

all event pages under Ubuntu Insights now get 404 messages. When I try and build new pages under Insights itself, it takes us back to the old format in preview mode. 

Is there a way that we can
>Have Events pages up and running again
>Ensure our old ones work too when we refer to previous events

**Comment by steverydz** [comment]
Closing as this doesn't appear to be an issue anymore
