### ISSUE TITLE
Uninviting call to action for email capture

### ISSUE THREAD

**Issue by Greggless** [canonical-websites/blog.ubuntu.com#297]
## Summary
- Not a compelling CTA, nobody likes filling their inbox with more emails
- Hidden content categories mean the is no incentive to click the 🔽 other than 'email updates'
![image](https://user-images.githubusercontent.com/23459065/38414252-e0a1d874-3985-11e8-94c0-ed7482250e54.png)

Maybe something like:

> Get the latest Insights from the world of cloud, server and IoT

**Comment by shivjoshi1996** [comment]
Not relevant anymore as we decided to go with the card-style layout for newsletter sign-ups (which has different text).
