### ISSUE TITLE
'Subscribe now' button is broken and is positioned outside the sign up card

### ISSUE THREAD

**Issue by kwm14** [canonical-websites/blog.ubuntu.com#308]
## Summary

Currently the 'Subscribe now' button is broken and is positioned outside the sign up card.
## Process

Issue can be found here: https://insights.ubuntu.com/2018/04/16/botsandus-build-a-social-robot-on-ubuntu

## Expected result

Buttons should be positioned inside the sign up card.

## Screenshot
![screen shot 2018-04-17 at 11 16 02](https://user-images.githubusercontent.com/17748020/38863814-bd3b68ec-4230-11e8-8a05-d67d9739ab96.png)

**Comment by caldav** [comment]
The reason is that it's sharing the same class as the other Marketo form at the bottom of the article, and picking up it's styling.

**Comment by steverydz** [comment]
@caldav Where is that custom CSS written? I suggest prefixing any instance of `.mktoButton` with `..p-post__content` e.g.

```
.p-post__content .mktoButton {
  ...
} 
```

**Comment by caldav** [comment]
It's imported from Marketo and we don't have control over it. Couldn't we get rid of the mktoButton class on the newsletter signup form? AFAICT, it's just a leftover from its Marketo -> Vanilla transition.

**Comment by steverydz** [comment]
This will be fixed in https://github.com/canonical-websites/blog.ubuntu.com/pull/379
