### ISSUE TITLE
No padding between hero section and list of cards

### ISSUE THREAD

**Issue by kwm14** [canonical-websites/blog.ubuntu.com#309]
## Summary

No padding between hero section and list of cards so the content is stacked on top of each-other.

## Process

Issue can be found here: https://insights.ubuntu.com/topics/design and also /juju, /maas and /snapcraft but once fixed it should update across all if templated.

## Screenshot
![screen shot 2018-04-17 at 11 25 18](https://user-images.githubusercontent.com/17748020/38864263-19196294-4232-11e8-9a77-9dff3e5b2154.png)

**Comment by shivjoshi1996** [comment]
This has now been fixed.
