### ISSUE TITLE
Insights hompage changes - build

### ISSUE THREAD

**Issue by shivjoshi1996** [canonical-websites/blog.ubuntu.com#313]

**Comment by frankiegranato** [comment]
This remains blocked until we review the proposed design with Marketing.

**Comment by anasereijo** [comment]
@steverydz final design and notes: https://github.com/canonical-websites/blog.ubuntu.com/issues/314
background image: https://assets.ubuntu.com/v1/a0bbf3ec-insights-grad-background.jpg
left side fold: https://assets.ubuntu.com/v1/b17a85da-insights-background-leftside-fold.png
right side fold: https://assets.ubuntu.com/v1/f6ea7ab1-insights-background-rightside-fold.png

**Comment by anasereijo** [comment]
**Design "What’s Coming up..." feature**

@steverydz final design: https://github.com/ubuntudesign/web-squad/issues/521

**Comment by steverydz** [comment]
@anasereijo Thanks. I've made a new issue for the what's coming up feature #346

**Comment by anasereijo** [comment]
@steverydz 
<img width="234" alt="screen shot 2018-05-04 at 11 47 43" src="https://user-images.githubusercontent.com/36884067/39624411-14bd0cf2-4f91-11e8-9bcd-2210317033a4.png">

Gradient Linear 30%

Location: 0%
Opacity 100% 
R= 13 G= 87 B= 119

Gradient slider: location 50%

Location: 90%
Opacity 100% 
R= 71 G= 146 B= 157

Gradient slider: location 50%

Location: 100%
Opacity 100% 
R= 71 G= 146 B= 157
