### ISSUE TITLE
Increase prominence of Featured content - design

### ISSUE THREAD

**Issue by pmahnke** [canonical-websites/blog.ubuntu.com#314]

**Comment by frankiegranato** [comment]
@anasereijo  Please design as if we are in a world where insights is called Blog.ubuntu.com. Also Please consider removing the subheading "Ubuntu news and resources". Sarah doesn't want to refer to news outside of the press centre.

**Comment by anasereijo** [comment]
I have designed different backgrounds with colour variations and selected a few.

**Colour options:**

![light grey](https://user-images.githubusercontent.com/36884067/39242065-aa82b15a-4880-11e8-9622-3afc7f65e5ad.jpg)
![sec colour blue](https://user-images.githubusercontent.com/36884067/39242070-abfdf7ec-4880-11e8-8f7c-358c50054885.jpg)
![sec colour green](https://user-images.githubusercontent.com/36884067/39242075-ae549c26-4880-11e8-9bae-3ae92c8a9ba5.jpg)
![sec colour green 2](https://user-images.githubusercontent.com/36884067/39242077-b00c23ea-4880-11e8-96c5-41bebf496a5a.jpg)
![dark aubergine 60](https://user-images.githubusercontent.com/36884067/39242078-b1a1983e-4880-11e8-8bef-4b5a2a52e5ef.jpg)

**Comment by spencerbygraves** [comment]
@anasereijo I like 1 & 4, I think @marcush is next in on Monday. Could you do a version with the coloured strips on the cards removed please. @frankiegranato I'd like to have a quick chat about that when you're free. Thanks.

**Comment by anthonydillon** [comment]
Do we need 3 featured posts? Could you make the latest featured post the
content of the hero banner without the box?

**Comment by anasereijo** [comment]
Hey @anthonydillon,
We used to have 1 featured article just bellow the title but marketing felt it wasn't prominent enough. They also asked to have more content above the fold so we removed the "Ubuntu blog" title and added 3 featured articles.
thank you

**Comment by anasereijo** [comment]
1.
![Uploading sec colour green - no strips.jpg…]()

2.
![light grey - no strips](https://user-images.githubusercontent.com/36884067/39254226-7f691538-48a1-11e8-935c-ebb5ce3c2401.jpg)

**Comment by nottrobin** [comment]
I prefer 1 to 2 from this set, but I actually prefer 2,3 and 5 from the previous set. I think the homepage needs some slightly stronger colours - at the moment it looks really boring, and adding a light grey background hardly helps.

Couldn't we do something to make the featured posts stand out a bit more? Make them look different from the rest of the cards?

**Comment by anasereijo** [comment]
@frankiegranato 

**Latest Version**
![insights-featured articles](https://user-images.githubusercontent.com/36884067/39516154-01da7b0e-4df4-11e8-88b0-e260049a55e1.jpg)

**Comment by frankiegranato** [comment]
I agree with @anasereijo about the preferred option being the one with coloured strips on the cards. We'll try to work with Marcus to reach a decision about colour tomorrow.

**Comment by anasereijo** [comment]
**Final Version**

-  h1 title removed
- "Featured posts" from 14px to 16px
- use of suru background with secondary colour to increase the prominence of Featured posts
- featured cards background with 90% opacity 
- Desktop label colour from #48929b to #FABA54 (wasn't visible when on a featured post)

![sec colour blue](https://user-images.githubusercontent.com/36884067/39619446-c2ed98e4-4f7f-11e8-8fcb-f2af960ccee1.jpg)

**Comment by nottrobin** [comment]
Great, that looks much nicer @anasereijo :champagne:
