### ISSUE TITLE
Missing spacing below title row on topic pages

### ISSUE THREAD

**Issue by nottrobin** [canonical-websites/blog.ubuntu.com#315]
Topic pages look like this:

![missing spacing](https://user-images.githubusercontent.com/519935/39058127-e52a951a-44b2-11e8-9a32-6c80db8df87d.png)

There should be space between the horizontal line and the article cards.

**Comment by anthonydillon** [comment]
@nottrobin thank you, I believe this may have been introduced on the homepage redesign.

**Comment by steverydz** [comment]
@anasereijo This looks like it's intentional as the other topics pages are screenshots on a dark background. The example @nottrobin has highlighted looks out of place.

Do you have any thoughts/suggestions on how this could/should look?

**Comment by anasereijo** [comment]
@steverydz I believe this has been fixed:

<img width="1140" alt="screen shot 2018-06-08 at 14 14 21" src="https://user-images.githubusercontent.com/36884067/41160012-48b2fa34-6b26-11e8-8e5d-4950112263e0.png">

**Comment by steverydz** [comment]
@anasereijo OK, thanks. I'll close this then.
