### ISSUE TITLE
Sign up button is misaligned and is the wrong colour

### ISSUE THREAD

**Issue by frankiegranato** [canonical-websites/blog.ubuntu.com#319]
Sign up button is misaligned and is the wrong colour. See screenshot: 
![screen shot 2018-04-23 at 16 05 13](https://user-images.githubusercontent.com/17002826/39135150-345b0e1c-4710-11e8-9469-f941c0ef60e1.png)
I suspect this error occurs when we have a pages.ubuntu form embedded inside an Insights page.

**Comment by shivjoshi1996** [comment]
@steverydz  Is this still an issue? I can't find a page which does this anymore.

**Comment by steverydz** [comment]
@shivjoshi1996 Yes it is, it's referenced also in #308. I'll close this as it's a duplicate
