### ISSUE TITLE
Fix padding between elements

### ISSUE THREAD

**Issue by anasereijo** [canonical-websites/blog.ubuntu.com#320]
we should have padding between hero image and the filters.

<img width="1395" alt="screen shot 2018-04-24 at 14 38 51" src="https://user-images.githubusercontent.com/36884067/39190846-5de0cc78-47cd-11e8-8ef5-0b2b047040c6.png">

**Comment by shivjoshi1996** [comment]
This seems to have been fixed, could you check again @anasereijo ?

**Comment by anasereijo** [comment]
@shivjoshi1996 fixed
