### ISSUE TITLE
Fix padding on insights

### ISSUE THREAD

**Issue by anasereijo** [canonical-websites/blog.ubuntu.com#321]
We should have padding between hero section and the cards.

<img width="1143" alt="screen shot 2018-04-24 at 14 41 10" src="https://user-images.githubusercontent.com/36884067/39190953-99793dd8-47cd-11e8-8c91-f8021b572660.png">

if we remove "u-no-padding" looks ok

**Comment by shivjoshi1996** [comment]
@anasereijo I think this has been fixed too?

**Comment by anasereijo** [comment]
@shivjoshi1996 yes, it's fixed
