### ISSUE TITLE
The type of post should not be plural.

### ISSUE THREAD

**Issue by frankiegranato** [canonical-websites/blog.ubuntu.com#329]
The type of post should not be plural. So, Webinars should be Webinar, and Articles should be Article.

**Comment by steverydz** [comment]
@anthonydillon This looks to be powered by the categories in WordPress. It looks like I can rename the categories display name and keep the slug as is. Does that sound like the right approach to you?

**Comment by anthonydillon** [comment]
@steverydz I believe WordPress had a field for a single display name. We should use that.

**Comment by steverydz** [comment]
@anthonydillon Yes, there are fields for plural and singular, however they are not part of the API response. It looks like they're custom fields or maybe added by a plugin as they're not part of WordPress natively?

The only other way I can think of to achieve this is to put logic in the templates e.g. 

```
{% if category.name == articles %}
Article
{% endif %}
```

but that's certainly not an ideal solution.

**Comment by anthonydillon** [comment]
@steverydz that seems messy. I don't like removing an `s` is its the last character as that can lead to unexpected behaviour in the future. I think the cleanest way to do this would be to enable the singular field in the API. We have done this for the author details.

**Comment by steverydz** [comment]
@anthonydillon Is that something I need to talk to IS about?

**Comment by anthonydillon** [comment]
@steverydz After considering the complexity of extending the API to include singular names over the usage I think it would be fine to do the if statements in the blog app. Sorry, for the rabbit hole.

It would be nice to implement it as an include so we could reuse the logic if needed.
