### ISSUE TITLE
Build 'Whats coming up' feature on blog homepage

### ISSUE THREAD

**Issue by steverydz** [canonical-websites/blog.ubuntu.com#346]
Design "What’s Coming up..." feature

@steverydz final design: ubuntudesign/web-squad#521

all icons used on events are from vanilla

Some extra fields will need to be created in WordPress and exposed in the API

**Comment by anasereijo** [comment]
@steverydz can you make "What's coming up" a h3 please? thanks

**Comment by anasereijo** [comment]
@steverydz updated Events & Webinars section:
![Uploading insights HP.jpg…]()

**Comment by steverydz** [comment]
@anasereijo :+1: Is the background colour the same?

**Comment by anasereijo** [comment]
@steverydz yes, we decided to keep the light grey and change the title
