### ISSUE TITLE
Link not working (full list of packages which are removed as part of the minimal install)

### ISSUE THREAD

**Issue by ShubhamDalal** [canonical-websites/blog.ubuntu.com#370]
## Summary

Link under Minimal Install at Page [blog](https://blog.ubuntu.com/2018/04/27/breeze-through-ubuntu-desktop-18-04-lts-bionic-beaver)

## Process

Visit [here](https://blog.ubuntu.com/2018/04/27/breeze-through-ubuntu-desktop-18-04-lts-bionic-beaver)
Find Minimal Install Paragraph
Inside paragraph Click here i.e. [here](https://bazaar.launchpad.net/~ubuntu-core-dev/ubuntu-seeds/ubuntu.bionic/view/head:/desktop.minimal-remove)

## Current and expected result

For current error please see Screenshot attached.

Expected Result must be the full list of packages which are removed as part of the minimal install.

## Screenshot

Error!
![screenshot from 2018-05-29 12-48-00](https://user-images.githubusercontent.com/13278287/40643714-abe6d8b8-633e-11e8-8c67-1437aba2db84.png)

**Comment by 8none1** [comment]
Correct link here:

https://git.launchpad.net/~ubuntu-core-dev/ubuntu-seeds/+git/ubuntu/tree/desktop.minimal-remove?h=bionic
