### ISSUE TITLE
Sign up for email updates formatting bug

### ISSUE THREAD

**Issue by JNunns** [canonical-websites/blog.ubuntu.com#373]
## Summary

Formatting issue on "Sign up for email updates blog" 

Tick boxes aren't in a line, they go off in an angle. 

## Process

I'm using an Asus Chromebook in this article: https://blog.ubuntu.com/2018/05/30/openstack-summit-vancouver-automating-the-data-centre 

Simply went into the article and noticed the odd formatting. 

## Current and expected result

The boxes are sloped like \ and they should be vertical. 

## Screenshot

![signupforemails](https://user-images.githubusercontent.com/39089063/40736539-374d278e-6436-11e8-9424-ee5647b78394.png)

**Comment by steverydz** [comment]
This looks like it was fixed in a recent update. 

@JNunns can you confirm if this is still an issue for you?

**Comment by JNunns** [comment]
Yes, this is still an issue for me.

**Comment by anasereijo** [comment]
fixed
