### ISSUE TITLE
wording can be improved to 'A first look at desktop metrics'

### ISSUE THREAD

**Issue by pmatulis** [canonical-websites/blog.ubuntu.com#381]
On

https://blog.ubuntu.com/2018/06/22/a-first-look-at-desktop-metrics

This sentence can use some work:

*This shows that we should make sure that custom partitioning is something we continue to offer, and it is we should investigate how we can make this easier.*

**Comment by 8none1** [comment]
Thanks for the feedback and the ping.

Changed to:  Most people choose to wipe their disks and reinstall from scratch.  The second most common option is to use a custom, manually created partition table.  Creating partition tables manually is an advanced process and we will investigate ways to make this easier.
