### ISSUE TITLE
/blog Fix card styling - Dev

### ISSUE THREAD

**Issue by anasereijo** [canonical-websites/blog.ubuntu.com#387]
## Screenshot

<img width="1650" alt="screen shot 2018-07-09 at 16 40 29" src="https://user-images.githubusercontent.com/36884067/42460875-ec88624c-8396-11e8-82c1-b8a17990ad8b.png">

**Comment by anthonydillon** [comment]
@anasereijo thanks, what do you recommend changing here? Add the descriptions to the first two articles?

**Comment by anasereijo** [comment]
@steverydz can you make tutorials label colour #47919e? can you also check if we are using it for another category? I had a look and seems that we are not but just double check.

I liked @anthonydillon suggestion about adding the descriptions to the first two articles. Can we try that too?

Many thanks
