### ISSUE TITLE
Redesign press centre (Landing page)

### ISSUE THREAD

**Issue by frankiegranato** [canonical-websites/blog.ubuntu.com#398]
Please remove/replace the photo of Mark (in the hero image)
Please include 'Archives'
Please include "Events" section
Please include "press", "contacts", "media resources" sections - secondary nav
Consider the ability to filter by "Type"

**Comment by anasereijo** [comment]
Hi @frankiegranato homepage is ready to be reviewd :)

### Homepage
![press centre homepage](https://user-images.githubusercontent.com/36884067/45021992-f9270880-b02a-11e8-83a2-2ff1b3b6c224.jpg)

**Comment by frankiegranato** [comment]
Looks lovely @anasereijo

**Comment by anasereijo** [comment]
This should be reviewed tomorrow with Sarah. I might have changes afterwards.
