### ISSUE TITLE
Link missing on "Announcing Extended Security Maintenance for Ubuntu 14.04 LTS – “Trusty Tahr” page

### ISSUE THREAD

**Issue by idobos71** [canonical-websites/blog.ubuntu.com#408]
## Summary
On the https://blog.ubuntu.com/2018/09/19/extended-security-maintenance-ubuntu-14-04-trusty-tahr page, the 'Commercetools' case is being mentioned but instead of a hyperlink to an article there is a "(link)" string only.

## Current and expected result
Instead of a "(link)" string the hyperlink should be provided.

**Comment by pmahnke** [comment]
@idobos71 it appears that this has been fixed, closing.

thanks for pointing it out.
