### ISSUE TITLE
Code font size is too big for super narrow layout

### ISSUE THREAD

**Issue by kyrofa** [canonical-websites/blog.ubuntu.com#415]
The font size of code sections is even bigger than the font size of the text. Add this to the fact that, due to the "Newsletter signup" sidebar, the actual content width is super narrow, adding any sensible code is very difficult to make look decent:

![screenshot from 2018-10-18 10-43-52](https://user-images.githubusercontent.com/946674/47173380-c1b2a980-d2c2-11e8-948c-c7a847f2e0c4.png)

Can we rework the width, code font size, or both to make it easier to put real code there?

**Comment by anasereijo** [comment]
This issue has been fixed and will be live on the next release. Thank you
