### ISSUE TITLE
blog post without category on the homepage (Build)

### ISSUE THREAD

**Issue by anasereijo** [canonical-websites/blog.ubuntu.com#425]
## Summary

Blog post not showing category or labels.

## Process

please make sure you estimate this issue
add a category to the post so it can have a label

## Screenshot

<img width="395" alt="screenshot 2018-11-02 at 15 40 50" src="https://user-images.githubusercontent.com/36884067/47925376-ed828180-deb5-11e8-8648-a7911f81a122.png">

**Comment by shivjoshi1996** [comment]
This has been done
