### ISSUE TITLE
New Zealand missing from snap infographic

### ISSUE THREAD

**Issue by timClicks** [canonical-websites/blog.ubuntu.com#431]
## Summary

The [2018-10 infographic](https://blog.ubuntu.com/2018/10/18/infographic-snaps-in-numbers) doesn't include New Zealand 🇳🇿 . I know that the map is labelled "Snaps are used in every major country worldwide", but it does include Iceland 🇮🇸 and Madagascar 🇲🇬 .  

![firefox_screenshot_2018-11-19t19-56-22 887z](https://user-images.githubusercontent.com/27889/48731583-3dc55600-eca2-11e8-9909-ffc25a0d06f3.png)

**Comment by waynecrosby** [comment]
Thanks for spotting that Tim, we would never knowingly miss out our commonwealth partners :) We'll update the infographic and re-issue it. Thanks again.
