### ISSUE TITLE
Lots of older blog posts don't have images

### ISSUE THREAD

**Issue by yaili** [canonical-websites/blog.ubuntu.com#433]
## Summary

Blogs posts that were migrated from design blog don't have images

## Process

Examples:
- https://blog.ubuntu.com/2015/07/16/the-monochromatic-makeover
- https://blog.ubuntu.com/2013/10/25/indented-styles-and-the-ubuntu-shape

## Current and expected result

I'd expect the images to still be there, as the posts aren't complete without them

**Comment by yaili** [comment]
Also a shame that the original author of the posts has been removed.

**Comment by matthewpaulthomas** [comment]
Both those examples are trying to include images from design.canonical.com, so this is a duplicate of #377.
