### ISSUE TITLE
/blog remove grey empty box from article - BUILD

### ISSUE THREAD

**Issue by anasereijo** [canonical-websites/blog.ubuntu.com#440]
## Summary

there is a grey (empty) section at the bottom of the article. please remove it

## Screenshot

<img width="1308" alt="screenshot 2018-12-11 at 09 33 44" src="https://user-images.githubusercontent.com/36884067/49791462-71871f00-fd28-11e8-87b1-ea0cac2bbdeb.png">

**Comment by shivjoshi1996** [comment]
( Found on the MicroK8s article: https://blog.ubuntu.com/2018/12/06/canonical-launches-microk8s-deploy-kubernetes-in-seconds ) 

Doesn't appear anywhere else.

**Comment by pmahnke** [comment]
I have edited the article, there was nothing obvious, but in saving, it has removed the box. I have also fixed the bullets, but it is currently cached, but should be better in a moment. Closing
