### ISSUE TITLE
blog - formatting issues on microk8s post

### ISSUE THREAD

**Issue by timClicks** [canonical-websites/blog.ubuntu.com#497]
There are several formatting issues in the [microk8s on raspberry pi article](https://blog.ubuntu.com/2019/02/27/single-node-kubernetes-on-raspberry-pi-microk8s-ubuntu). Several code sections are not in code blocks. which means (among other things) that many # signs are exposed on the left-hand side, making it hard to read.

An example:

> Let’s deploy a test workload and then try to access it in on our command line and remotely from another machine. Run the command to deploy the cats container: 
>
> microk8s.kubectl run –image=nginx nginx –port=80
>
> microk8s.kubectl run –image=nginx nginx –port=80microk8s.kubectl  expose deployment nginx –port 80 –target-port 80 –type ClusterIP  –selector=run=nginx –name nginx-svc  
>
> \# from this command, we can get the clusterIP for our container watch microk8s.kubectl get all
> \# you should see a line like this: service/nginx-svc	ClusterIP   10.152.183.91   <none>    	80/TCP	82s
> \# You can now access the container on this IP and port:wget 10.152.183.91:80
> \# … you should be greeted with the nginx welcome page!
>
> You can clean-up microk8s installation by running the following command:
>
> sudo microk8s.reset

**Comment by anasereijo** [comment]
@caldav is this something you can help us with?

**Comment by pmahnke** [comment]
@timClicks thanks for this.  I have attempted to fix up.

closing
