### ISSUE TITLE
post about past conference is on "upcoming events and webinars" section

### ISSUE THREAD

**Issue by anasereijo** [canonical-websites/blog.ubuntu.com#506]
## Summary

"FOSDEM 2019, a recap" post is on "Upcoming events and webinars" section.
This doesn't make sense because this post is a recap about a conference, not a post about a future conference.

## Process

I'm not sure why this is happening but could it be that someone added an event tag or simply decided it should be there? This needs to be investigated to prevent happening again.

## Screenshot

![Screenshot 2019-03-18 at 10 33 18](https://user-images.githubusercontent.com/36884067/54524278-7b44a200-4969-11e9-967e-b10feb58abf1.png)

**Comment by anasereijo** [comment]
@pmahnke can you please estimate this? thank you

**Comment by pmahnke** [comment]
@anasereijo - fixed, just had to say it was an article, not an event in wordpress
