### ISSUE TITLE
bug on the post navigation and author image broken

### ISSUE THREAD

**Issue by anasereijo** [canonical-websites/blog.ubuntu.com#507]
## Summary

- [x] Something wrong is happening with the navigation 
- [ ] Author profile picture is broken

## Screenshot

<img width="1440" alt="Screenshot 2019-03-18 at 11 20 36" src="https://user-images.githubusercontent.com/36884067/54527227-24db6180-4971-11e9-8b85-118b57341473.png">

**Comment by pmahnke** [comment]
@anasereijo I fixed the 'navigation' issue, it was that html was allowed in the meta og:description field; however, the user's picture is deej's issue, perhas ping him to see if he can update it?

**Comment by anasereijo** [comment]
@pmahnke once it's reviewed I think we can close it. I get in touch with the user about the profile pic.
